### PR TITLE
ci: msrv after build

### PR DESCRIPTION
**Pull request by yanganto**

### CODE REVIEW

**Review by storopoli — APPROVED** [review]
Thanks again man! You're awesome.

**Comment by storopoli** [comment]
Yeah we have the same `error[E0786]: found invalid metadata files` in the clippy tasks.
What if we called `cargo clean` before `cargo clippy` and add a `# TODO:` comment on top of that, once the bug is fixed upstream?

**Comment by yanganto** [comment]
Yeh, now I think the bug is inside the cache, so I removed the cache for job needs clippy.

**Review by storopoli — APPROVED** [review]
Seems to be working now.
Feel free to merge.

**Comment by yanganto** [comment]
Yes, let me try a while if still not work, I will move the clippy and checks on stable.  I still not sure why our crates can not build by clippy, but we can use stable instead and fix the clippy x msrv issue in other PR.

**Comment by storopoli** [comment]
We have a `clippy.toml` in the root dir, so I am not that worried about using stable for clippy lints.

**Comment by yanganto** [comment]
Okay, I think it is not worthy to dig this now.

**Comment by storopoli** [comment]
Ok I'll squash everything into a single commit into the original PR.
Man, thanks again! :)

**Pull request merged**
